name: BlueArcade
version: 1.6.1
main: net.blueva.arcade.Main
author: Blueva
website: blueva.net
softdepend: [PlaceholderAPI]
api-version: 1.16
commands:
  arcade:
    aliases: [ba, barcade, partygames, pg]
    description: Base command
    usage: /arcade [action]